### ISSUE TITLE
README.md doesn't say where to find my QTile configuration.

### ISSUE THREAD

**Issue by kennethstailey** [aravinda0/qtile-bonsai#6]
Dear friend,

I noticed that your `README.md` file does not say what file that the `QTile` configuration is in.

Thanks and regards,
Kenneth Stailey

**Comment by aravinda0** [comment]
Hey there.

I figure the config file location is a `qtile` concern that you would have sorted out by following the qtile documentation  (which I've linked to in the installation section) and have figured out before incorporating `qtile-bonsai`.

Still, since it won't add any extra noise to the docs by adding a link, I've done so in 05c81cc :)

**Comment by kennethstailey** [comment]
Very clever. Thanks.
